name: Frontend CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 2025년 최신 프로젝트를 위한 Node 22

      - name: Install dependencies & Build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_STATIC_EXPORT: "true"
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_KAKAO_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}
          NEXT_PUBLIC_KAKAO_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_KAKAO_REDIRECT_URI }}
          NEXT_PUBLIC_OAUTH_KAKAO_EXCHANGE_PATH: ${{ secrets.NEXT_PUBLIC_OAUTH_KAKAO_EXCHANGE_PATH }}
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_DEBUG_OAUTH: ${{ secrets.NEXT_PUBLIC_DEBUG_OAUTH }}
        run: |
          npm ci
          npm run build
        working-directory: ./songdap

      - name: Make zip file
        run: |
          # Next.js의 static export 결과물인 'out' 폴더로 이동
          cd songdap/out 
          cp ../appspec.yml .
          cp -r ../scripts .
          cp -r ../nginx .
          zip -r ../../frontend.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./frontend.zip s3://${{ secrets.S3_BUCKET_NAME }}/frontend.zip

      - name: CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=frontend.zip